version: "3.3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.1G"

  backend:
    container_name: backend
    build: 
      context: ./backend      
    restart: unless-stopped
    ports:
      - "4000:4000" 
    depends_on:
      - "database"
    links:
      - "database:db"    
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "1G"
    networks:
      - "backend"

  database:
    container_name: database
    image: postgres:12-alpine
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    networks:
      - "backend"

networks:
  backend:
    driver: bridge       